"""Explicit execution of a verified, materialized module selection."""

from __future__ import annotations

import hashlib
import importlib
import keyword
import os
import re
import sys
from collections.abc import Callable, Iterator, Mapping
from pathlib import Path
from tempfile import TemporaryDirectory
from types import MappingProxyType, ModuleType
from typing import Any

from .registry import (
    Registry,
    RegistryError,
    _name,
    _no_symlinks,
    _root_path,
    _wheel_files,
    canonical_bytes,
)


class ImportBundle(Mapping[str, Any]):
    """A completed set of bindings with an immutable visible namespace.

    The exports themselves can contain mutable state. Bundle identity describes
    the selected artifacts and aliases, not a fresh runtime instance or the
    arbitrary Python callback supplied to ``atomic_import(link=...)``.
    """

    def __init__(
        self,
        exports: Mapping[str, Any],
        identity: str,
        target: Path,
        value: Any,
        external_requirements: tuple[str, ...],
    ):
        self._exports = MappingProxyType(dict(exports))
        self._identity = identity
        self._target = target
        self._value = value
        self._external_requirements = external_requirements

    def __getitem__(self, key: str) -> Any:
        return self._exports[key]

    def __iter__(self) -> Iterator[str]:
        return iter(self._exports)

    def __len__(self) -> int:
        return len(self._exports)

    @property
    def exports(self) -> Mapping[str, Any]:
        return self._exports

    @property
    def value(self) -> Any:
        return self._value

    @property
    def identity(self) -> str:
        return self._identity

    @property
    def target(self) -> Path:
        return self._target

    @property
    def external_requirements(self) -> tuple[str, ...]:
        return self._external_requirements


def atomic_import(
    registry: Registry,
    locks: Mapping[str, dict],
    target: str | Path,
    *,
    link: Callable[[Mapping[str, Any]], Any] | None = None,
) -> ImportBundle:
    """Prepare an entire coherent import, then expose one completed bundle.

    All lock metadata, artifact hashes, file ownership, and files are checked
    before any selected module is imported. A failed load or link returns no
    partial bundle. Python import/factory effects and sys.modules state are not
    rolled back. External distributions are reported, not environment-locked.
    """
    if not isinstance(locks, Mapping) or not locks:
        raise ValueError("an import bundle requires at least one named member lock")
    if any(
        not isinstance(alias, str)
        or not alias.isidentifier()
        or keyword.iskeyword(alias)
        for alias in locks
    ):
        raise ValueError("bundle aliases must be non-keyword Python identifiers")
    if link is not None and not callable(link):
        raise ValueError("link must be callable")
    locked = {alias: registry._verify_lock(locks[alias]) for alias in sorted(locks)}
    artifacts, external = {}, set()
    for lock in locked.values():
        external.update(lock["external_requirements"])
        for artifact in lock["artifacts"]:
            name = _name(artifact["distribution"])
            if name in artifacts and artifacts[name] != artifact:
                raise RegistryError(
                    f"incompatible artifact versions in one import bundle: {name}"
                )
            artifacts[name] = artifact
    files = {}
    for name in sorted(artifacts):
        artifact = artifacts[name]
        for filename, content in _wheel_files(
            registry._blob(artifact["sha256"]), artifact
        ).items():
            if filename in files:
                raise RegistryError(f"multiple artifacts own bundle path: {filename}")
            files[filename] = content
    identity = hashlib.sha256(
        canonical_bytes(
            {
                "format": "module-families-import-v1",
                "bindings": {name: item["sha256"] for name, item in locked.items()},
            }
        )
    ).hexdigest()
    parent = _root_path(Path(target))
    _no_symlinks(parent)
    parent.mkdir(parents=True, exist_ok=True)
    site = parent / f"b_{identity}"

    def verify_existing():
        _no_symlinks(site)
        if not site.is_dir():
            raise RegistryError("prepared bundle target is not a directory")
        for filename, content in files.items():
            path = site / filename
            _no_symlinks(path)
            if not path.is_file() or path.read_bytes() != content:
                raise RegistryError(f"prepared bundle content conflicts: {filename}")
        # Bytecode caches generated by this interpreter are permitted; other
        # files would expand the verified installation boundary.
        for path in site.rglob("*"):
            _no_symlinks(path)
            if (
                path.is_file()
                and str(path.relative_to(site)) not in files
                and "__pycache__" not in path.parts
            ):
                raise RegistryError(
                    f"unexpected file in prepared bundle: {path.relative_to(site)}"
                )

    if site.exists() or site.is_symlink():
        verify_existing()
    else:
        with TemporaryDirectory(prefix=".prepare-", dir=parent) as staging_name:
            staging = Path(staging_name) / "site"
            staging.mkdir()
            for filename, content in sorted(files.items()):
                path = staging / filename
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_bytes(content)
            try:
                os.rename(staging, site)
            except OSError:
                if not site.exists():
                    raise
                verify_existing()
    exports = MappingProxyType(
        {alias: _import_member(lock["member"], site) for alias, lock in locked.items()}
    )
    value = link(exports) if link is not None else exports
    return ImportBundle(exports, identity, site, value, tuple(sorted(external)))


def load(registry: Registry, lock: dict, target: str | Path) -> Any:
    """Verify and materialize a module lock, then import its selected export.

    This executes trusted Python in the caller's process. The module lock covers
    generated artifacts; external Python dependencies belong to the environment.
    Content-named modules share ordinary Python module state within the process.
    Source verification cannot detect arbitrary in-memory monkeypatching; the
    interpreter and its import hooks remain part of the trusted environment.
    """
    result = registry.materialize(lock, Path(target))
    return _import_member(lock["member"], Path(result["target"]))


def _import_member(member: dict, target: Path) -> Any:
    """Import a prepared member, rejecting foreign cached generated modules.

    The caller must first verify and materialize the complete dependency closure.
    This helper checks source origins; it is not an in-process Python sandbox.
    """
    target = Path(target)
    if target.is_symlink():
        raise ValueError("materialized target must not be a symlink")
    target = target.resolve()
    module_name, export = member["import_module"], member["export"]
    if not re.fullmatch(r"mf_members\.m_[a-f0-9]{64}", module_name):
        raise ValueError("invalid generated member import path")
    if not isinstance(export, str) or not export.isidentifier():
        raise ValueError("invalid member export")
    relative = Path(*module_name.split(".")).with_suffix(".py")
    if not (target / relative).is_file():
        raise ValueError("locked member module is absent from materialized artifacts")
    # Python consults sys.modules before loading source. Check every generated
    # module available in the prepared site, including shared dependency cells.
    # Byte-identical sources in another verified site may share module identity.
    for namespace, prefix in (("mf_cells", "c"), ("mf_members", "m")):
        for expected in (target / namespace).glob(f"{prefix}_*.py"):
            if not re.fullmatch(rf"{prefix}_[a-f0-9]{{64}}", expected.stem):
                continue
            name = f"{namespace}.{expected.stem}"
            if name not in sys.modules:
                continue
            cached = sys.modules[name]
            if not isinstance(cached, ModuleType):
                raise ValueError(f"{name} has an invalid cached module")
            source = vars(cached).get("__file__")
            if not isinstance(source, str):
                raise ValueError(f"{name} has no verifiable cached source")
            source_path = Path(source)
            if source_path.is_symlink():
                raise ValueError(f"{name} has a symlinked cached source")
            try:
                matches = (
                    source_path.is_file()
                    and source_path.read_bytes() == expected.read_bytes()
                )
            except OSError as exc:
                raise ValueError(f"{name} has an unreadable cached source") from exc
            if not matches:
                raise ValueError(
                    f"{name} cached source differs from materialized artifact"
                )
    # Namespace roots must remain PEP 420 namespaces, including in the ambient
    # interpreter. A foreign package initializer would execute before the cell.
    for namespace in ("mf_cells", "mf_members"):
        for suffix in (
            importlib.machinery.SOURCE_SUFFIXES
            + importlib.machinery.BYTECODE_SUFFIXES
            + importlib.machinery.EXTENSION_SUFFIXES
        ):
            if (target / namespace / ("__init__" + suffix)).exists():
                raise ValueError(
                    f"{namespace} target contains an ordinary package initializer"
                )
        existing = sys.modules.get(namespace)
        if existing is not None and getattr(existing, "__file__", None) is not None:
            raise ValueError(f"{namespace} is occupied by an ordinary Python package")
        spec = importlib.util.find_spec(namespace)
        if spec is not None and spec.origin is not None:
            raise ValueError(f"{namespace} is shadowed by an ordinary Python package")
    if str(target) not in sys.path:
        sys.path.insert(0, str(target))
    importlib.invalidate_caches()
    return getattr(importlib.import_module(module_name), export)
