"""Evidence-preserving model-output parsers and deterministic policies."""

from .admission import (
    AdmissionDecision,
    AdmissionDisposition,
    AdmissionSignals,
    AdmissionThresholds,
    admit_candidate,
)
from .aggregation import (
    ScalarEstimate,
    WeightedContribution,
    WeightedMean,
    WeightedObservation,
    weighted_mean,
    wilson_proportion,
)
from .answers import (
    AnswerDisposition,
    GroundedAnswer,
    parse_answer,
    parse_answer_candidates,
)
from .artifacts import (
    Activity,
    ArtifactRef,
    KnowledgeArtifact,
    KnowledgeScope,
    ReviewState,
)
from .assertions import (
    Assertion,
    AssertionUpdateKind,
    AssertionUpdatePlan,
    all_of,
    any_of,
    group_assertions,
    plan_assertion_update,
    valid_at,
)
from .changesets import (
    ChangesetIssue,
    ChangesetIssueKind,
    KnowledgeChangeEntry,
    KnowledgeChangeset,
    PositionedKnowledgeEdit,
    validate_knowledge_changeset,
)
from .consolidation import (
    ConsolidationBudget,
    ConsolidationPlan,
    PromotionSignal,
    plan_consolidation,
)
from .decisions import parse_decisions
from .derivations import (
    DerivationInput,
    DerivationIssue,
    DerivationIssueKind,
    DerivationReport,
    KnowledgeDerivation,
    KnowledgeOrigin,
    inspect_knowledge_derivations,
)
from .evidence import (
    ArtifactEvidence,
    EvidenceIssue,
    EvidenceIssueKind,
    EvidenceValidationReport,
    LocatedEvidence,
    LocatedEvidenceIssue,
    LocatedEvidenceReport,
    document_evidence_ref,
    validate_artifact_evidence,
    validate_located_evidence,
)
from .excerpt import excerpt
from .experience import (
    EXPERIENCE_KNOWLEDGE_VERSION,
    ChangeEvaluation,
    ExperienceKnowledgeCandidate,
    ExperienceKnowledgeKind,
    ExpertFeedback,
    FeedbackDiagnosis,
    FeedbackRootCause,
    KnowledgeChangeProposal,
    KnowledgeEdit,
    KnowledgeFile,
    KnowledgeStructureIssue,
    KnowledgeStructureIssueKind,
    KnowledgeStructureReport,
    KnowledgeUse,
    KnowledgeUseManifest,
    TrajectoryEvidence,
    build_knowledge_use_manifest,
    inspect_knowledge_structure,
    parse_experience_knowledge,
    parse_feedback_diagnoses,
    parse_knowledge_change,
)
from .fact_scans import fact_scan_revisions, pending_fact_sections
from .facts import (
    FactAssessment,
    deduplicate_fact_candidates,
    normalize_claim,
    parse_claim_assessments,
    parse_facts,
)
from .freshness import (
    FreshnessReport,
    FreshnessStatus,
    KnowledgeDependency,
    ReferenceFreshnessReport,
    ReferenceRevisionChange,
    RevisionChange,
    assess_dependencies,
    assess_freshness,
    assess_revision_refs,
    evidence_dependencies,
    impacted_artifacts,
)
from .glossary import parse_glossary
from .links import (
    DEFAULT_SIMILARITY_LIMIT,
    DEFAULT_SIMILARITY_THRESHOLD,
    LinkCandidate,
    derive_links,
    extract_explicit_links,
)
from .mutations import (
    MemoryDecision,
    MemoryMutation,
    MemoryMutationPlan,
    MemoryOperation,
    apply_memory_mutations,
    plan_memory_mutations,
)
from .observations import (
    KnowledgeObservation,
    KnowledgeObservationReport,
    KnowledgeObservationStage,
    ObservationIssue,
    ObservationIssueKind,
    inspect_knowledge_observations,
)
from .refinement import RefinementEdit, parse_refinement
from .research import (
    MemorySignal,
    NoteEvolutionPlan,
    SalientMemory,
    plan_note_evolution,
    rank_salient_memories,
)
from .scoring import grounding_coverage
from .sections import document_sections, section_revisions
from .segmentation import TopicSegment, hybrid_topic_segments
from .summaries import (
    DigestSummary,
    DigestTopic,
    ImpactAssessment,
    parse_digest,
    parse_impact,
)
from .tags import (
    TagAssignments,
    TagDefinition,
    assign_tags,
    normalize_tag,
    search_weight,
)
from .versions import VersionFamily, resolve_version_families

__all__ = [
    "Activity",
    "ArtifactEvidence",
    "ArtifactRef",
    "Assertion",
    "AssertionUpdateKind",
    "AssertionUpdatePlan",
    "ScalarEstimate",
    "AdmissionDecision",
    "AdmissionDisposition",
    "AdmissionSignals",
    "AdmissionThresholds",
    "ConsolidationBudget",
    "ConsolidationPlan",
    "ChangesetIssue",
    "ChangesetIssueKind",
    "DEFAULT_SIMILARITY_LIMIT",
    "DEFAULT_SIMILARITY_THRESHOLD",
    "AnswerDisposition",
    "DigestSummary",
    "DigestTopic",
    "DerivationInput",
    "DerivationIssue",
    "DerivationIssueKind",
    "DerivationReport",
    "FactAssessment",
    "EvidenceIssue",
    "EvidenceIssueKind",
    "EvidenceValidationReport",
    "LocatedEvidence",
    "LocatedEvidenceIssue",
    "LocatedEvidenceReport",
    "EXPERIENCE_KNOWLEDGE_VERSION",
    "ChangeEvaluation",
    "ExperienceKnowledgeCandidate",
    "ExperienceKnowledgeKind",
    "ExpertFeedback",
    "FeedbackDiagnosis",
    "FeedbackRootCause",
    "FreshnessReport",
    "FreshnessStatus",
    "GroundedAnswer",
    "KnowledgeDependency",
    "ReferenceFreshnessReport",
    "ReferenceRevisionChange",
    "KnowledgeDerivation",
    "KnowledgeOrigin",
    "KnowledgeChangeEntry",
    "KnowledgeChangeset",
    "KnowledgeObservation",
    "KnowledgeObservationReport",
    "KnowledgeObservationStage",
    "KnowledgeChangeProposal",
    "KnowledgeEdit",
    "KnowledgeFile",
    "KnowledgeStructureIssue",
    "KnowledgeStructureIssueKind",
    "KnowledgeStructureReport",
    "KnowledgeUse",
    "KnowledgeUseManifest",
    "KnowledgeArtifact",
    "KnowledgeScope",
    "ImpactAssessment",
    "LinkCandidate",
    "MemoryDecision",
    "MemoryMutation",
    "MemoryMutationPlan",
    "MemoryOperation",
    "MemorySignal",
    "NoteEvolutionPlan",
    "ObservationIssue",
    "ObservationIssueKind",
    "PositionedKnowledgeEdit",
    "PromotionSignal",
    "RefinementEdit",
    "RevisionChange",
    "ReviewState",
    "SalientMemory",
    "TagAssignments",
    "TagDefinition",
    "TopicSegment",
    "TrajectoryEvidence",
    "WeightedContribution",
    "WeightedMean",
    "WeightedObservation",
    "VersionFamily",
    "admit_candidate",
    "all_of",
    "any_of",
    "build_knowledge_use_manifest",
    "apply_memory_mutations",
    "assess_dependencies",
    "assess_freshness",
    "assess_revision_refs",
    "assign_tags",
    "derive_links",
    "deduplicate_fact_candidates",
    "document_sections",
    "document_evidence_ref",
    "evidence_dependencies",
    "excerpt",
    "extract_explicit_links",
    "fact_scan_revisions",
    "grounding_coverage",
    "group_assertions",
    "hybrid_topic_segments",
    "inspect_knowledge_structure",
    "inspect_knowledge_derivations",
    "inspect_knowledge_observations",
    "impacted_artifacts",
    "normalize_claim",
    "parse_answer",
    "parse_answer_candidates",
    "parse_claim_assessments",
    "parse_decisions",
    "parse_digest",
    "parse_facts",
    "parse_experience_knowledge",
    "parse_feedback_diagnoses",
    "parse_glossary",
    "parse_impact",
    "parse_knowledge_change",
    "parse_refinement",
    "plan_memory_mutations",
    "plan_assertion_update",
    "plan_consolidation",
    "plan_note_evolution",
    "pending_fact_sections",
    "rank_salient_memories",
    "resolve_version_families",
    "normalize_tag",
    "search_weight",
    "section_revisions",
    "valid_at",
    "validate_artifact_evidence",
    "validate_located_evidence",
    "validate_knowledge_changeset",
    "weighted_mean",
    "wilson_proportion",
]

from .citations import (
    CitationDeclarationReport,
    CitationDeclarationStatus,
    CitationEvent,
    CitationEventKind,
    OwnedEvidenceRef,
    inspect_citation_declarations,
)
from .compaction import (
    CompactionEvidence,
    CompactionExclusion,
    CompactionTrace,
    EvidenceCompactionPlan,
    EvidenceGroup,
    plan_evidence_compaction,
)
from .multimodal import (
    AssetBinding,
    AssetSelection,
    EvidenceAsset,
    RetainedAsset,
    select_evidence_assets,
)

__all__ += [
    "CitationEvent",
    "CitationEventKind",
    "CitationDeclarationReport",
    "CitationDeclarationStatus",
    "OwnedEvidenceRef",
    "inspect_citation_declarations",
    "CompactionEvidence",
    "CompactionExclusion",
    "CompactionTrace",
    "EvidenceGroup",
    "EvidenceCompactionPlan",
    "plan_evidence_compaction",
    "EvidenceAsset",
    "AssetBinding",
    "RetainedAsset",
    "AssetSelection",
    "select_evidence_assets",
]
