"""Fixtures generated by cited upstream code, independent of Mari implementation."""

import io
import itertools
import json
import random
from pathlib import Path

import pytest

from mark_kit.algorithms.compression import fastcdc_chunks
from mark_kit.algorithms.lexical import BM25Variant, BM25VariantIndex
from mark_kit.algorithms.linkage import BlockingPredicate, learn_blocking

FIXTURES = Path(__file__).parent / "fixtures" / "algorithms"


@pytest.mark.parametrize("variant", list(BM25Variant))
def test_bm25_upstream_scores(variant):
    data = json.loads((FIXTURES / "bm25.json").read_text())
    index = BM25VariantIndex(
        {str(i): tokens for i, tokens in enumerate(data["corpus"])}, variant=variant
    )
    actual = [
        index.explain(data["query"], str(i)).score for i in range(len(data["corpus"]))
    ]
    assert actual == pytest.approx(data["scores"][variant.value], abs=1e-12)


def test_fastcdc_go_reference_boundaries():
    fixture = json.loads((FIXTURES / "fastcdc.json").read_text())
    state = 12345
    data = bytearray()
    for _ in range(16384):
        state = (1664525 * state + 1013904223) & 0xFFFFFFFF
        data.append(state >> 24)
    chunks = tuple(
        fastcdc_chunks(io.BytesIO(data), minimum=64, average=256, maximum=1024)
    )
    assert [len(chunk.data) for chunk in chunks] == fixture["lengths"]
    assert b"".join(chunk.data for chunk in chunks) == data


def test_blocking_matches_exhaustive_oracle():
    rng = random.Random(24)
    matches = frozenset("abcde")
    for _ in range(20):
        predicates = [
            BlockingPredicate(
                str(i),
                frozenset(m for m in sorted(matches) if rng.random() < 0.5),
                rng.randint(1, 10),
            )
            for i in range(7)
        ]
        possible = [
            subset
            for count in range(8)
            for subset in itertools.combinations(predicates, count)
            if frozenset().union(*(p.covered_pairs for p in subset)) == matches
        ]
        result = learn_blocking(predicates, matches)
        assert result.optimal
        assert result.feasible == bool(possible)
        if possible:
            assert result.cost == min(
                sum(p.comparison_cost for p in subset) for subset in possible
            )
